export const PRODUCTS = [
    // TRUCK BEDS
    {
        id: "1",
        name: "Toyota Hilux Long Bed",
        description:
            "OEM Toyota Hilux long bed in excellent condition. Minor surface scuffs only. Fits 2005–2015 models. Includes tailgate, bed rails, and all mounting hardware.",
        price: 850,
        category: "Truck Beds",
        condition: "Used – Good",
        year: "2010",
        make: "Toyota",
        model: "Hilux",
        images: ["/images/bed1.jpg", "/images/bed2.jpg"],
        in_stock: true,
        featured: true,
        created_at: "2025-01-10T10:00:00Z",
    },
    {
        id: "2",
        name: "Chevy Silverado 1500 Short Bed",
        description:
            "White Chevy Silverado 1500 short bed. No major dents. Tailgate functional. Ready to install. Fits 2014–2018 Silverado 1500.",
        price: 650,
        category: "Truck Beds",
        condition: "Used – Good",
        year: "2016",
        make: "Chevrolet",
        model: "Silverado 1500",
        images: ["/images/bed2.jpg"],
        in_stock: true,
        featured: true,
        created_at: "2025-01-15T10:00:00Z",
    },
    {
        id: "3",
        name: "Ford F-150 Styleside Bed 6.5ft",
        description:
            "Clean F-150 Styleside bed, white, 6.5ft. Minimal rust. Includes bed liner. Fits 2009–2014 F-150. All mounting brackets included.",
        price: 700,
        category: "Truck Beds",
        condition: "Used – Fair",
        year: "2012",
        make: "Ford",
        model: "F-150",
        images: ["/images/bed1.jpg"],
        in_stock: true,
        featured: false,
        created_at: "2025-02-01T10:00:00Z",
    },
    {
        id: "4",
        name: "Toyota Hilux Short Bed – Black",
        description:
            "Black OEM Hilux short bed. Excellent structural condition. Minor paint fade. Tailgate and side rails included. Fits 2016–2022 Hilux.",
        price: 950,
        category: "Truck Beds",
        condition: "Used – Excellent",
        year: "2018",
        make: "Toyota",
        model: "Hilux",
        images: ["/images/bed2.jpg"],
        in_stock: true,
        featured: true,
        created_at: "2025-02-10T10:00:00Z",
    },
    // DOORS
    {
        id: "5",
        name: "Dodge Ram 1500 Front Driver Door",
        description:
            "Gold/tan Dodge Ram 1500 front driver-side door. Glass intact. Mirror mount present. Minor scratches. Fits 1994–2001 Ram.",
        price: 180,
        category: "Doors",
        condition: "Used – Good",
        year: "1998",
        make: "Dodge",
        model: "Ram 1500",
        images: ["/images/doors.jpg"],
        in_stock: true,
        featured: true,
        created_at: "2025-01-20T10:00:00Z",
    },
    {
        id: "6",
        name: "GMC Sierra Front Passenger Door – Green",
        description:
            "OEM GMC Sierra 1500 passenger door, forest green. Glass intact. Door panel included. Fits 1999–2006 Sierra.",
        price: 165,
        category: "Doors",
        condition: "Used – Good",
        year: "2002",
        make: "GMC",
        model: "Sierra 1500",
        images: ["/images/doors.jpg"],
        in_stock: true,
        featured: false,
        created_at: "2025-01-25T10:00:00Z",
    },
    {
        id: "7",
        name: "Toyota Hilux Front Door Pair",
        description:
            "Matched pair of front doors (driver + passenger) from a Toyota Hilux. White finish. Both windows functional. Excellent seals.",
        price: 350,
        category: "Doors",
        condition: "Used – Excellent",
        year: "2014",
        make: "Toyota",
        model: "Hilux",
        images: ["/images/doors.jpg"],
        in_stock: true,
        featured: false,
        created_at: "2025-02-05T10:00:00Z",
    },
    // HILUX PARTS
    {
        id: "8",
        name: "Hilux Tailgate – White OEM",
        description:
            "OEM Toyota Hilux tailgate, white. All handle hardware intact. Hinges included. Fits 2005–2021 Hilux models.",
        price: 280,
        category: "Hilux Parts",
        condition: "Used – Good",
        year: "2015",
        make: "Toyota",
        model: "Hilux",
        images: ["/images/bed1.jpg"],
        in_stock: true,
        featured: true,
        created_at: "2025-02-12T10:00:00Z",
    },
    {
        id: "9",
        name: "Hilux Rear Bumper Assembly",
        description:
            "Complete rear bumper assembly for Toyota Hilux. Chrome finish. No cracks. Fits 2015–2022 standard and double cab.",
        price: 195,
        category: "Hilux Parts",
        condition: "Used – Good",
        year: "2018",
        make: "Toyota",
        model: "Hilux",
        images: ["/images/bed2.jpg"],
        in_stock: false,
        featured: false,
        created_at: "2025-02-14T10:00:00Z",
    },
    {
        id: "10",
        name: "Hilux Roll Bar / Sport Bar",
        description:
            "Heavy-duty stainless roll bar for Toyota Hilux. Polished finish. Bolt-on installation. Compatible with 2005–2022 Hilux.",
        price: 420,
        category: "Hilux Parts",
        condition: "Used – Excellent",
        year: "2019",
        make: "Toyota",
        model: "Hilux",
        images: ["/images/bed1.jpg"],
        in_stock: true,
        featured: true,
        created_at: "2025-02-18T10:00:00Z",
    },
    // BODY PARTS
    {
        id: "11",
        name: "Hilux Front Fender (Right)",
        description:
            "Right-side front fender for Toyota Hilux, white. No major dents. Bolt holes intact. Fits 2015–2022 Hilux.",
        price: 130,
        category: "Body Parts",
        condition: "Used – Good",
        year: "2017",
        make: "Toyota",
        model: "Hilux",
        images: ["/images/bed2.jpg"],
        in_stock: true,
        featured: false,
        created_at: "2025-02-20T10:00:00Z",
    },
    {
        id: "12",
        name: "F-150 Hood",
        description:
            "Ford F-150 hood, white. Hinges included. Minor hail damage on one side. Great for a repair project. Fits 2004–2008 F-150.",
        price: 250,
        category: "Body Parts",
        condition: "Used – Fair",
        year: "2006",
        make: "Ford",
        model: "F-150",
        images: ["/images/bed1.jpg"],
        in_stock: true,
        featured: false,
        created_at: "2025-02-22T10:00:00Z",
    },
];

export const REVIEWS = [
    {
        id: "r1",
        author: "Marcus Thompson",
        rating: 5,
        comment:
            "Found a perfect Hilux bed here for half the price of a dealer. The condition was exactly as described – no surprises. The crew even helped me load it up and gave me some tips on the install. If you need Hilux parts in East Texas, this is the only place to go.",
        location: "Tyler, TX",
        verified: true,
        avatar: "https://i.pravatar.cc/150?u=marcus",
        created_at: "2025-11-15T10:00:00Z",
    },
    {
        id: "r2",
        author: "Jessica Rodriguez",
        rating: 5,
        comment:
            "Great selection of truck beds! I found exactly what I needed for my Silverado 1500 within minutes of arriving. The staff is knowledgeable and the prices are the best I've found after calling five other yards. Fast response on the live chat too!",
        location: "Corsicana, TX",
        verified: true,
        avatar: "https://i.pravatar.cc/150?u=jessica",
        created_at: "2025-12-03T10:00:00Z",
    },
    {
        id: "r3",
        author: "Desmond Lewis",
        rating: 5,
        comment:
            "Drove all the way from Waco to pick up a set of doors for my Ram. They were in great shape and the price was more than fair. You can tell these guys take pride in their inventory. Honest business and great service.",
        location: "Waco, TX",
        verified: true,
        avatar: "https://i.pravatar.cc/150?u=desmond",
        created_at: "2026-01-08T10:00:00Z",
    },
    {
        id: "r4",
        author: "Craig Miller",
        rating: 4,
        comment:
            "Solid selection of Hilux parts. I got a tailgate and a sport bar. Both fit perfectly on my 2018 model. Only reason for 4 stars is it took a little while to get someone on the phone initially, but once I got through, the service was top-notch.",
        location: "Huntsville, TX",
        verified: true,
        avatar: "https://i.pravatar.cc/150?u=craig",
        created_at: "2026-01-20T10:00:00Z",
    },
    {
        id: "r5",
        author: "Amanda Chen",
        rating: 5,
        comment:
            "Best truck parts yard I've dealt with. Clean parts, fair pricing, and they actually know their inventory. The Hilux short bed I bought was immaculate. They even had the matching tail lights I was looking for.",
        location: "Nacogdoches, TX",
        verified: true,
        avatar: "https://i.pravatar.cc/150?u=amanda",
        created_at: "2026-02-02T10:00:00Z",
    },
    {
        id: "r6",
        author: "Bobby King",
        rating: 5,
        comment:
            "AG Truck Beds is the real deal. Professional service, fair quotes, and they had my part pulled and ready for pickup the same day I called. If you're looking for quality used beds or body panels, don't waste time elsewhere.",
        location: "Buffalo, TX",
        verified: true,
        avatar: "https://i.pravatar.cc/150?u=bobby",
        created_at: "2026-02-18T10:00:00Z",
    },
];

export const CATEGORIES = [
    "Truck Beds",
    "Hilux Parts",
    "Doors",
    "Body Parts",
];

export const STATS = [
    { label: "Parts in Stock", value: "500+" },
    { label: "Happy Customers", value: "1,200+" },
    { label: "Years Experience", value: "10+" },
    { label: "Same-Day Pickups", value: "Daily" },
];
